### ISSUE TITLE
Would you like to tell me how to use your great pylof

### ISSUE THREAD

**Issue by Lyshen** [damjankuznar/pylof#1]
Hello~  I just know the LOF algorithm today and I want to use this algorithm on a 3D point set to cluster the outliers.  I find your great work on git, but I don't quite understand  how to use your lof file. Would you like to show me the way please? Thank you for your patience.

**Comment by damjankuznar** [comment]
Hi,
I updated the README (https://github.com/damjankuznar/pylof) with some examples on how to use pylof. Please have a look at let me know if that answers your questions.

**Comment by Lyshen** [comment]
Oh, great examples!!!  I get the way of using it.  Thank you very much :+1:
