### ISSUE TITLE
Apply it on 1D data

### ISSUE THREAD

**Issue by marjanm** [damjankuznar/pylof#2]
Hi

I know the input data must be in a form of tuple. But, I can't apply it on 1 dimensional data:

 return lof.outliers(1, data)
  File "C:\Users\lof.py", line 162, in outliers
    value = l.local_outlier_factor(k, instance)
  File "C:\Users\lof.py", line 95, in local_outlier_factor
    return local_outlier_factor(min_pts, instance, self.instances, distance_function=self.distance_function)
  File "C:\Users\lof.py", line 141, in local_outlier_factor
    (k_distance_value, neighbours) = k_distance(min_pts, instance, instances, **kwargs)
  File "C:\Users\lof.py", line 104, in k_distance
    distance_value = distance_function(instance, instance2)
  File "C:\Users\lof.py", line 33, in distance_euclidean
    if len(instance1) != len(instance2):
TypeError: object of type 'float' has no len()

Do you have any suggestion? 

Also do you have any advice on how to use it on large scale data?

Thanks

**Comment by Lyshen** [comment]
Hi. 

For the first question, it seems that on 1 dimensional data the instances are not in a form of tuple, right? Actually, I had implemented LOF in Java after learning your code in Python for my poor experience&skill on Python (I think I need to practice and learn more from now on T T). 

In the Java implement, the input data are stored in a list and I check the instance1 and instance2 are in the same dimension and it works.  

For the second question, I read your code and find that you don't use the the KD-tree in the k_distance method. Instead, you sort the distance every time which is inefficient way to get the K distances of a point. What's more, I think implement a multithreading version may help to deal with larger scale data. 

KD-tree has many open source implement and you can easily increase your code's performance on larger scale data. 

I hope my suggestions may be helpful for you. Thanks~

**Comment by marjanm** [comment]
Hi

Thanks for replying.

Yes, I am not expert in python too. I found out for one element you have to put comma to make it a tuple :-)

I will try to add KD-tree to it.

Thanks!

**Comment by damjankuznar** [comment]
@Lyshen Thanks for the KD-tree tip. Yes I agree, the code is far from optimized. My main goal was to get "vanilla" implementation of LOF in Python. However, I encourage you to implement such improvements and send me pull request and we can all benefit from the improvements.
