### ISSUE TITLE
idx out of range for knn when len(distances) < k

### ISSUE THREAD

**Issue by kierkegaard13** [damjankuznar/pylof#8]
If the instance you're running lof for is the same distance away from most points, the distances list can have a length < k in which case distances[k - 1][0] returns an index out of range error

**Comment by damjankuznar** [comment]
First of, thanks for already submitting a fix.
Second, could you maybe also provide a test case (input data) to replicate the error. It will be also useful in future regression testing.

**Comment by kierkegaard13** [comment]
No problem.. I added the test case you asked for.

**Comment by Mistasong39** [comment]
Has this been fixed? I'm having the same error right now .

**Comment by kierkegaard13** [comment]
You can pull my fork, since I fixed it there. For some reason, the author
hasn't accepted my pr in months.

**Comment by damjankuznar** [comment]
Thanks. I merged your fix. Sorry for the delay.

**Comment by kierkegaard13** [comment]
Cool thanks.
